modLoader="javafml"
loaderVersion="[46,)"
license="BSD (3 clause)"
issueTrackerURL="https://github.com/gigaherz/ToolBelt/issues"

[[mods]]
modId="toolbelt"
version="${file.jarVersion}"
displayName="Tool Belt"
description='''
Declutter your inventory of tools
'''
displayURL="https://github.com/gigaherz/ToolBelt"
logoFile="logo.png"
authors="gigaherz"

[[dependencies.toolbelt]]
   modId="forge"
   mandatory=true
   versionRange="[46.0.12,)"
   ordering="NONE"
   side="BOTH"
[[dependencies.toolbelt]]
   modId="minecraft"
   mandatory=true
   versionRange="[1.20,1.21)"
   ordering="NONE"
   side="BOTH"
[[dependencies.toolbelt]]
   modId="sewingkit"
   mandatory=false
   versionRange="[1.8.0,)"
   ordering="NONE"
   side="BOTH"